import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(
    page_title="Tier 5: Microbiome 16S rRNA Showcase | GenomeTech Studio",
    page_icon="🦠",
    layout="wide"
)

st.markdown("""
<style>
    .stApp {
        background: radial-gradient(circle at top right, #1e1b4b 0%, #0f172a 60%, #020617 100%);
        color: #f1f5f9 !important;
        font-family: 'Inter', sans-serif;
    }
    .tier-header {
        background: linear-gradient(90deg, #10b981 0%, #047857 100%);
        padding: 2rem;
        border-radius: 16px;
        margin-bottom: 2rem;
        border: 1px solid rgba(52, 211, 153, 0.4);
    }
    .showcase-card {
        background: rgba(30, 41, 59, 0.7);
        border: 1px solid rgba(16, 185, 129, 0.3);
        border-radius: 12px;
        padding: 1.5rem;
        margin-bottom: 1.5rem;
    }
</style>
""", unsafe_allow_html=True)

# Navigation header back to main website
if st.button("← Back to GenomeTech Studio"):
    st.markdown('<meta http-equiv="refresh" content="0;url=https://bhumikasihare.github.io/genometech-studio/">', unsafe_allow_html=True)

st.markdown("""
<div class="tier-header">
    <span style="background: rgba(255,255,255,0.2); padding: 4px 12px; border-radius: 999px; font-size: 0.8rem; font-weight: bold;">TIER 5 SHOWCASE DASHBOARD</span>
    <h1 style="color: white; margin-top: 10px;">Microbiome (16S rRNA) Profiling Suite (Demo Pipeline)</h1>
    <p style="color: #a7f3d0; margin: 0;">Interactive demonstration of our amplicon sequencing analysis pipeline using QIIME2, featuring OTU picking, taxonomic classification, and alpha/beta diversity metrics.</p>
</div>
""", unsafe_allow_html=True)

# Layout split: Left side explains pipeline methods; Right side displays live demo results
col1, col2 = st.columns([1, 1.5], gap="large")

with col1:
    st.markdown('<div class="showcase-card">', unsafe_allow_html=True)
    st.markdown("### 🧬 Pipeline Architecture & Methods")
    st.markdown("""
    This showcase demonstrates the robust computational steps executed in our **Tier 5 Microbiome 16S rRNA** pipeline:
    
    1. **Demultiplexing & Denoising:** DADA2 quality filtering, chimera removal, and Amplicon Sequence Variant (ASV) resolution.
    2. **Taxonomic Assignment:** Naive Bayes classifier trained on SILVA/Greengenes reference databases.
    3. **Alpha & Beta Diversity:** Calculation of Chao1, Shannon, Simpson indices, and Bray-Curtis dissimilarity matrices.
    4. **Differential Abundance (ANCOM/LEfSe):** Identifying biomarker taxa discriminating between experimental cohorts.
    """)
    st.markdown("---")
    st.markdown("**Deliverables Included in Tier 5:**")
    st.markdown("- QIIME2 Artifacts & Visualizations (`.qzv`)")
    st.markdown("- High-Resolution Taxonomic Relative Abundance Barplots")
    st.markdown("- Alpha/Beta Diversity PCoA Plots (Vector SVG)")
    st.markdown("- Cleaned ASV Count & Taxonomy Tables (CSV/Excel)")
    st.markdown('</div>', unsafe_allow_html=True)

with col2:
    st.markdown('<div class="showcase-card">', unsafe_allow_html=True)
    st.markdown("### 📊 Live Taxonomic Breakdown (Demo Dataset)")
    st.markdown("Inspect relative abundance and diversity metrics generated by our automated pipeline:")
    
    # Mock microbiome summary table
    mock_microbiome = pd.DataFrame({
        "Phylum": ["Firmicutes", "Bacteroidetes", "Actinobacteria", "Proteobacteria", "Verrucomicrobia"],
        "Dominant Genera": ["Faecalibacterium, Roseburia", "Bacteroides, Prevotella", "Bifidobacterium", "Escherichia, Klebsiella", "Akkermansia"],
        "Mean Relative Abundance (%)": [52.4, 31.8, 8.2, 5.1, 2.5],
        "Alpha Diversity (Chao1 Index)": [342.1, 289.4, 198.2, 145.0, 92.6]
    })
    
    st.dataframe(mock_microbiome, use_container_width=True)
    st.markdown('</div>', unsafe_allow_html=True)

# Full-width section below for interactive bar chart preview
st.markdown('<div class="showcase-card">', unsafe_allow_html=True)
st.markdown("### 🔬 Sample-Wise Taxonomic Composition Barplot")
st.markdown("Demonstration of relative phylum-level distribution across control and treatment experimental groups:")

# Generate mock bar chart data
np.random.seed(100)
chart_data = pd.DataFrame(
    np.random.rand(5, 3) * 100,
    index=['Sample_Control_1', 'Sample_Control_2', 'Sample_Treatment_1', 'Sample_Treatment_2', 'Sample_Treatment_3'],
    columns=['Firmicutes', 'Bacteroidetes', 'Proteobacteria']
)
st.bar_chart(chart_data, use_container_width=True)
st.markdown('</div>', unsafe_allow_html=True)